# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
        config.build_settings.delete('CODE_SIGNING_ALLOWED')
        config.build_settings.delete('CODE_SIGNING_REQUIRED')
    end
end
target 'Top12' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'RAMAnimatedTabBarController' ,'~>3.5.0'
pod 'Alamofire', '~> 4.5'
pod 'SideMenu', '~> 3.1'
pod 'SwiftyJSON'
pod 'GoogleMaps'
pod 'GooglePlaces'
pod 'GooglePlacePicker'
pod 'Kingfisher' , '~> 5.0'
pod 'Localize-Swift', '~> 2.0'
pod 'ActionSheetPicker-3.0', '~> 2.3.0'
pod 'SwiftMessages' ,'~>5.0.1'
pod 'MIAlertController', '~> 1.3.0'
pod 'NVActivityIndicatorView'
pod 'ImageSlideshow', '~> 1.6.1'
pod 'ImageSlideshow/Kingfisher'
pod 'NotificationBannerSwift', '~>1.6.3'
pod 'ChainableAnimations', '~> 3.0.1'
pod 'HCSStarRatingView'
pod 'NumberMorphView', '0.2.0'
pod 'MIAlertController', '~> 1.3'
pod 'IQKeyboardManagerSwift'
pod 'MarqueeLabel/Swift', '3.1.6'

pod 'ESTabBarController-swift'
pod 'Socket.IO-Client-Swift', '~> 13.3.0'
pod 'Starscream', '<= 3.0.5'
pod 'KMPlaceholderTextView', '~> 1.4.0'
pod 'UIView+Shimmer'
pod 'Firebase/Core'
pod 'Firebase/Messaging'
pod 'PMSuperButton'
pod 'SkyFloatingLabelTextField'
pod 'OpalImagePicker', '~> 1.4.0'


  # Pods for Top12

  target 'Top12Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Top12UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
